#
# Created by Android Team MIS-SEG Year 2021
# Project-wide Gradle settings.
#

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Support 16 KB page sizes
android.useV2VectorPacking=true
# Enable 16 KB page alignment for native libraries globally
android.jniLibs.use16kPages=true
# Ensure native libraries are uncompressed in the APK (required for direct memory mapping)
android.bundle.enableUncompressedNativeLibs=true
